---
title: "Foundations of Functional Programming with purrr"
author: "Marcus Becker"
date: "July 14, 2019"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)

```

# Chapter 1: Simplifying Iteration and Lists With purrr

```{r}

# purrr makes iteration easy - it wraps a for loop into a single function: map

# Iteration is the process of doing the same process to multiple inputs. 

# map(object, function) - object can be a vector or a list

object1 <- list(first = c(1, 2, 3),
               second = c(4, 5, 6),
               third = c(7, 8, 9))

map(object, sum)

object2 <- list(first = c("1", "2", "3"),
                second = c("4", "5", "6"),
                third = c("7", "8", "9"))

class(object2$first)
class(object2[[1]])
class(object2[["first"]]) 

# Change each element from a character to a number using a for loop

for (i in seq_along(object2)) {
  object2[[i]] <- as.numeric(object2[[i]])
}

print(object2) # now are numbers. 

# How about using map? Let's change back to character.

object2 <- map(object2, as.character)

print(object2) # back to characters. 

# Subsetting lists - slightly different than a df

mtcars[1, "mpg"] # in a df, use square brackets - first number is the row, second is the column. Or,
mtcars$mpg

# now, a list on the other hand ...
object2[[1]] # first element
object2[["first"]] # can also call it by name using quotes. 

# Let's load the repurrrsive package
library(repurrrsive)

data("wesanderson")
str(wesanderson)
str(wesanderson[[1]]) # GrandBudapest
str(wesanderson$GrandBudapest)
wesanderson[[1]][3] # pull out third element of the first vector

data("sw_films")

str(sw_films)
sw_films[[1]]["title"] # A New Hope!

# The many flavours of map - standard map() just returns a list.

map_dbl() # double, a type of numeric. Gives us a vector. 
map_lgl() # logical
map_chr() # character

map(wesanderson, length) # is equivalent to ...
map(wesanderson, ~ length(.x)) # OK. But this notation is convenient for ...
map_dbl(wesanderson, ~ length(.x))
map_dfr(wesanderson, ~length(.x))

object3 <- data.frame(numcolors = map_dbl(wesanderson, ~ length(.x))) %>%
  rownames_to_column(var = "Movie") # cool. 

```

# Chapter 2: More Complex Iterations

```{r}

names(wesanderson) # Find out names of objects in a list.

# If no names, use set_names() in a pipe
sw_films_named <- sw_films %>%
  set_names(map_chr(., "title"))

names(sw_films_named)

# Idea for ABMI work: store species data in a list, then use map to iteratively run models on those species. Cool. 

# Simulating data 

sites <- list("north", "east", "west")

list_of_df <- map(sites,
                  ~ data.frame(sites = .x,
                               a = rnorm(mean = 5, n = 200, sd = (5/2)),
                               b = rnorm(mean = 200, n = 200, sd = 15)))

list_of_df[[1]]

# Run a linear model

list_of_df %>%
  map(~ lm(a ~ b, data = .)) %>%
  map(summary)

# map() variants

map(sw_films, ~ .x[["director"]]) # gives list
map_chr(sw_films, ~.x[["director"]]) # gives character vector

map(sw_films, ~.x[["episode_id"]])
map_dbl(sw_films, ~.x[["episode_id"]])

# map2() and pmap()

# map2 takes two lists as two arguments: .x and .y

means <- list(1, 2, 3)
sites <- list("north", "west", "east")

list_maps2 <-  map2(.x = means, .y = sites, ~ data.frame(sites = .y, a = rnorm(mean = .x, n = 200, sd = (5/2))))

list_maps2

# pmap for more than two lists as inputs - requires us to supply our lists a little bit differently.

# create MASTER LIST first

```

# Chapter 3: Troubleshooting Lists with purrr

```{r}

safely()

data("sw_people")

str(sw_people)

height_cm <- map(sw_people, ~.x[["height"]])

height_cm <- map(sw_people, "height") %>% # equivalent to above.
  map(function(x) {
    ifelse(x == "unknown", NA, as.numeric(x))
  })

# Using possibly()

height_cm %>%  
  map_dbl(possibly(function(x){
  # Convert centimeters to feet
    x * 0.0328084
}, otherwise = NA_real_)) 

# Using walk() - keeps things quiet. 

# uses a .x and .f argument, just like map()

# works well with plots - no output to the console

data("gap_split")

plots <- map2(.x = gap_split[1:10], .y = names(gap_split[1:10]),
              ~ ggplot(.x, mapping = aes(x = year, y = lifeExp)) +
                geom_line() +
                labs(title = "Life expectancy through time"))

walk(plots, print)
  
```

# Chapter 4: Problem Solving with purrr

```{r}

data("gh_repos")

str(gh_repos)

gh_repos_names <- gh_repos %>%
  map_chr(~ .x[[1]]$owner$login) %>%
  set_names(gh_repos, .)

gh_users_named <- gh_users %>%
  set_names(map_chr(., "name"))

names(gh_users_named)

# Determine who joined github first
map_chr(gh_users, ~.x[["created_at"]]) %>%
      set_names(map_chr(gh_users, "name")) %>%
    sort() # Looks like Jenny Bryan!

# Determine user versus organization
map_lgl(gh_users, ~.x[["type"]] == "User")


# Determine who has the most public repositories
map_int(gh_users, ~.x[["public_repos"]]) %>%
    set_names(map_chr(gh_users, "name")) %>%
    sort()

# Even more complex problems

# e.g. gh_repos is very long and complex.
# Which repository is the largest?
map(gh_repos,
    ~ map_dbl(.x, ~ .x[["size"]])) %>%
  # Grab the largest element
  map(~max(.x))

# Making plots

# ggplot does not accept lists as input (only df) - so purrr can be used to go from list -> df using map_df

map_df(gh_users, `[`, # this is the function here - apply [] to each list with login, name, etc as the arguments passed to []
       c("login", "name", "followers", "public_repos")) %>%
  ggplot(., aes(x = followers, y = public_repos)) +
  geom_point()


map_chr(sw_films, "title")

# Turn data into correct dataframe format
film_by_character <- tibble(filmtitle = map_chr(sw_films, "title")) %>%
    mutate(filmtitle, characters = map(sw_films, "characters")) %>%
    unnest()

# Pull out elements from sw_people
sw_characters <- map_df(sw_people, `[`, c("height","mass","name","url"))

# Join our two new objects
character_data <- inner_join(film_by_character, sw_characters, by = c("characters" = "url")) %>%
    # Make sure the columns are numbers
    mutate(height = as.numeric(height), mass = as.numeric(mass))

# Plot the heights, faceted by film title
ggplot(character_data, aes(x = height)) +
  geom_histogram(stat = "count") +
  facet_wrap(~ filmtitle)


```














